name: flutter_statusbar_manager
description: Flutter Statusbar Manager, lets you control the status bar color, style (theme), visibility, and translucent properties across iOS and Android.
version: 2.0.0
homepage: https://github.com/FooStudio/flutter_statusbar_manager

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.foo.flutterstatusbarmanager
        pluginClass: FlutterStatusbarManagerPlugin
      ios:
        pluginClass: FlutterStatusbarManagerPlugin

